#!/usr/bin/env python3
"""Generate docs from the dumps: <mod>_<version>/diff_legacy.md per mod and README.md.

Usage: python3 build_docs.py   (run after dump_cvars.py; output is deterministic, no timestamps)
       python3 build_docs.py --selftest
"""
import argparse
import re
import sys
from pathlib import Path

MAP = "fueldump"  # local map the game hosts for the dumps (dump_cvars.py)
OUT = Path(__file__).resolve().parent
BASE = "legacy"
COLOR = re.compile(r"\^[0-9a-zA-Z]")
# engine commands mod code is allowed to remove (src/qcommon/cmd.c Cmd_RemoveCommandSafe)
REMOVABLE = ["+lookup", "-lookup", "+lookdown", "-lookdown", "configstrings"]


def dumps():
    """{mod: newest dump folder}: <mod>_<version>/ with a cvars.tsv; older versions stay but are ignored."""
    best = {}
    for f in OUT.glob("*_*/cvars.tsv"):
        mod, _, ver = f.parent.name.rpartition("_")
        if re.fullmatch(r"\d+(\.\d+)*", ver) and (key := tuple(map(int, ver.split(".")))) > best.get(mod, ((),))[0]:
            best[mod] = (key, f.parent)
    return {mod: p for mod, (_, p) in sorted(best.items())}


def read_tsv(path):
    rows = path.read_text(encoding="utf-8").splitlines()
    header = rows[0].split("\t")
    # cvar and command names are case-insensitive in the engine (Q_stricmp lookups)
    return {r.split("\t")[0].lower(): dict(zip(header, r.split("\t"))) for r in rows[1:]}


def is_client(cvar):
    """Client-side and not set by the server: systeminfo (s) is copied from the server, read-only (R)
    is set by code only (src/client/cl_parse.c CL_SystemInfoChanged, src/qcommon/cvar.c)."""
    return cvar["side"] == "client" and not set(cvar["flags"]) & set("sR")


def load(folder):
    cvars = read_tsv(folder / "cvars.tsv")
    client = {k: v for k, v in cvars.items() if is_client(v)}
    return cvars, client, read_tsv(folder / "cmds.tsv")


def arch(folder):
    """Architecture of the loaded client modules, from the Sys_LoadDll lines."""
    for line in (folder / "console.log").read_text(encoding="utf-8").splitlines():
        if m := re.match(r"^Sys_LoadDll\(\S+\.(x86_64|i386)\.so\)\.\.\. succeeded$", line):
            return m[1]
    return "unknown"


def engine(folder):
    for line in (folder / "console.log").read_text(encoding="utf-8").splitlines():
        if line.startswith(("ET Legacy", "^2ET Legacy")):
            return COLOR.sub("", line)
    return "unknown"


def table(rows, columns):
    if not rows:
        return "none\n"
    cell = lambda s: s.replace("|", "\\|") or " "
    lines = ["| " + " | ".join(columns) + " |", "|" + "---|" * len(columns)]
    lines += ["| " + " | ".join(cell(r.get(c, "")) for c in columns) + " |" for r in rows]
    return "\n".join(lines) + "\n"


def diff(base, mod):
    return [mod[k] for k in sorted(mod.keys() - base.keys())], [base[k] for k in sorted(base.keys() - mod.keys())]


def diff_doc(name, base_name, base_cg, base_cmds, cg, cmds):
    text = (f"# {name} vs {base_name}\n\n"
            f"Generated by `build_docs.py`. Commands from `cmds.tsv`, cvars from `cvars.tsv` (client-side only, see README). "
            f"Added = in {name}, not in {base_name}. Missing = in {base_name}, not in {name} (values shown from {base_name}). "
            f"Names compared case-insensitively.\n\n"
            f"Engine commands mods may remove (`src/qcommon/cmd.c` `Cmd_RemoveCommandSafe`): "
            f"{', '.join(f'`{c}`' for c in REMOVABLE)}. The legacy cgame removes them, so if listed as added here, "
            f"the mod kept the engine command rather than adding its own.\n\n")
    for title, b, m, cols in (("Commands", base_cmds, cmds, ["name", "description"]),
                              ("Client cvars", base_cg, cg, ["name", "flags", "source", "default"])):
        added, missing = diff(b, m)
        text += f"## {title} added ({len(added)})\n\n{table(added, cols)}\n"
        text += f"## {title} missing ({len(missing)})\n\n{table(missing, cols)}\n"
    return text


def main():
    folders = dumps()
    if BASE not in folders:
        sys.exit(f"no {BASE} dump in {OUT}: run dump_cvars.py {BASE} first")
    base_dir = folders[BASE]
    _, base_cg, base_cmds = load(base_dir)

    rows = []
    for mod, folder in folders.items():
        cvars, cg, cmds = load(folder)
        row = {"folder": f"`{folder.name}/`", "arch": arch(folder), "engine": engine(folder),
                              "cvars": str(len(cvars)), "client": str(len(cg)), "commands": str(len(cmds))}
        if mod == BASE:
            row.update({"cmds +/-": "base", "client +/-": "base"})
        else:
            (folder / "diff_legacy.md").write_text(diff_doc(folder.name, base_dir.name, base_cg, base_cmds, cg, cmds), encoding="utf-8")
            (ca, cm), (ga, gm) = diff(base_cmds, cmds), diff(base_cg, cg)
            row.update({"cmds +/-": f"+{len(ca)} / -{len(cm)}", "client +/-": f"+{len(ga)} / -{len(gm)}"})
        rows.append(row)

    (OUT / "README.md").write_text(README.format(
        map=MAP, base=base_dir.name,
        mods=table(rows, ["folder", "arch", "engine", "cvars", "client", "commands", "cmds +/-", "client +/-"]),
    ), encoding="utf-8")
    print("\n".join(f"{r['folder']} cmds {r['cmds +/-']}, client {r['client +/-']}" for r in rows))


README = """# Cvar / command dumps per mod

Generated by `build_docs.py`, do not edit by hand. Edit the template in `build_docs.py` instead.

What exists in each mod, taken from the running game instead of old docs: engine + mod `cvarlist` and `cmdlist`, and a diff of every mod against ET: Legacy ({base}) as the base.

## Workflow

Requirements: Python 3.9+, standard library only; the scripts run from any working directory. `dump_cvars.py` and `diff_profile.py` need `ETLEGACY_SRC` in `settings.conf` (asked by `deploy.sh`) or the environment to tell client from server engine cvars.

```
python3 research/dumps/dump_cvars.py [mod ...]   # 1. launch the game per mod, dump lists (needs display, run outside sandbox)
python3 research/dumps/dump_cvars.py --list      #    show what would run per mod, start nothing
python3 research/dumps/dump_cvars.py --parse <dir> ...  #    re-parse an existing console.log + modules.tsv without launching
python3 research/dumps/build_docs.py             # 2. regenerate diff_legacy.md files and this README
python3 research/dumps/diff_profile.py           # 3. compare against the cvars the profile sets (diff_profile.md, profile_unused.md)
```

`dump_cvars.py`:

1. Finds the mods: every real directory in `<fs_homepath>` except `etmain` and `profiles`, plus `legacy`. legacy is the installed game's mod: its pk3 is `<fs_basepath>/legacy/legacy_v<version>.pk3` with the version of `GAME_BIN_I386 --version`. Any other mod's original pk3 is the newest file named `<mod>[-_]v?<version>.pk3` in `<fs_homepath>/<mod>` or `<fs_basepath>/<mod>` (versions compare numerically, `_` and `.` both separate). Renamed or patched pk3s don't match. If several files match the newest version, it asks which one on the terminal (without a terminal that mod fails). The output folder is `<mod>_<version>` with dots.
2. Runs every mod with the 32-bit client (`GAME_BIN_I386` in `settings.conf`; `GAME_BIN` and the x86_64 `qagame` if it is not set) so all dumps share one engine build. Its `fs_basepath` is not `BASEPATH` of `settings.conf`: the client has its own install path, read once per run from the search path of the dedicated server next to it (`etlded` for `etl`). legacy is the pk3 and server module of that install. Needs the mod's `qagame.mp.i386.so` to host the map locally; mods without one are not dumped.
3. Copies the original pk3 and the server module (from `<fs_homepath>/<mod>`) into a temporary `fs_homepath`, deleted at exit. No profile, no autoexecs, no other pk3s are there, so `value` is the code default unless the engine or mod changed it at startup.
4. Starts `<client> +set fs_homepath <tmp> +set fs_game <mod> +set dedicated 0 +set r_fullscreen 0 +set r_mode -1 +set r_customwidth 640 +set r_customheight 480 +set dump_marker 1 +map {map}`. Local hosting loads client and server modules, so cvars of engine, ui, cgame and qagame are all registered. The engine unpacks cgame/ui from the pk3 into the temporary homepath.
5. Waits for `CL_InitCGame:` in the console output, 5 s more, then writes `cvarlist;cmdlist` to the game's stdin (non-tty stdin is read as console input, `src/sys/con_tty.c`), then `quit`.
6. Saves `console.log`, `modules.tsv` (strings of the loaded cgame/ui/qagame binaries: `side<TAB>string`, side `client` or `server`; the binaries vanish with the temporary homepath) and parses the lists by their footers (`<n> total cvars`, `<n> cvar indexes`, `<n> commands`) into TSV, with each cvar's side (see below).
7. A run that ends before the `cmdlist` footer (crash, cgame never loaded, timeout) writes nothing and the other mods continue. The final report lists dumped, skipped (no original pk3, no `qagame`) and failed mods, with the game's own error lines or the exit code.

`build_docs.py` takes the newest dump folder per mod and compares each against {base}: commands (all) and client-side cvars, by name, case-insensitive, sorted. Output depends only on the dump files.

## Client-side cvars

The dumps hold server cvars too (local hosting loads qagame). Compared are only cvars the client controls: `side` = `client` in `cvars.tsv`, minus flags `s` and `R`.

`side` / `source` (`dump_cvars.py` `classify`):

- `engine`: registered (`Cvar_Get*`) or created (`Cvar_Set`) by the engine in the ET: Legacy source. `src/server` = server; everything else (client, renderer, sdl, qcommon) = client. `sv_*` = server.
- `cgame/ui` / `qagame`: mod cvar whose name occurs as a string only in the loaded cgame/ui or only in the qagame binary (`modules.tsv`). Works for closed-source mods.
- `both` (name in both binaries) or `-` (in neither, names built at runtime like `session%i`): client if userinfo (`U`) or prefixed `cg_`/`cl_`/`ui_`, else server (ui host-game menu settings, cgame mirrors of server values like `g_gametype`, session data).

How the server still changes client cvars (source: `src/client/cl_parse.c` `CL_SystemInfoChanged`, `src/game/g_svcmds.c`):

- systeminfo: the client copies every key of the server's systeminfo string, but only into cvars flagged `s` (plus `pmove_fixed`, `pmove_msec`, `g_synchronousClients`). `s` cvars are excluded.
- cheat (`C`): reset to default while `sv_cheats` is 0. Kept, the flags column shows them.
- `sv_cvar` restrictions: server admins can force any client cvar into a range (e.g. `sv_cvar cl_maxpackets IN 60 125`); depends on the server, so not reflected here.

## What cvars do

The dumps only show which cvars exist, not what they do. Sources for descriptions:

- Current, authoritative for the base game (engine + legacy mod): [ET: Legacy cvar docs](https://etlegacy.readthedocs.io/en/latest/cvars.html) and the ET: Legacy source (`<ET: Legacy source checkout>`).
- Older lists, useful for descriptions of vanilla/mod cvars: [antman.info cvar list](https://antman.info/wolf/cvar/), [fearless-assassins.com ET cvars](https://fearless-assassins.com/enemy-territory-cvars.html/). **Outdated** (ET 2.60b era): some cvars don't exist or behave differently in ET: Legacy. Check against the dumps here and the legacy docs/source before using them.

## Mods

{mods}
`arch` = architecture of the loaded client modules. `cvars` excludes user-created cvars. `client` = client-side cvars. `cmds +/-` / `client +/-` = added / missing compared to the base; details in each folder's `diff_legacy.md`.

## Files per folder

- `console.log`: full console output of the run (raw lists included)
- `modules.tsv`: `side, string`; whitespace-free strings of the loaded module binaries, used to sort mod cvars into client / server
- `cvars.tsv`: `name, flags, value, default, side, source`; cvars registered by engine, ui, cgame or qagame
- `cmds.tsv`: `name, description`; client-side commands (engine + mod). Server-side client commands handled only by qagame are not listed by `cmdlist`.
- `diff_legacy.md` (not in base): commands and client cvars added / missing compared to the base
- `diff_profile.md`: client cvars the profile never sets, and cvars it sets that are server-side in this mod. The profile side is every cvar set anywhere in the mod's live exec chain (from `<fs_homepath>/<mod>/autoexec*.cfg`, following `exec` in files and aliases); `profile_unused.md` (in `dumps/`) lists names set there that exist in no dumped mod

## Flags (`src/qcommon/cvar.c` `Cvar_List_f`)

`S` serverinfo, `s` systeminfo, `U` userinfo, `R` read-only, `I` init (command line only), `A` archive (saved to etconfig.cfg), `L` latched (applies after restart), `C` cheat, `P` protected, `T` temp, `N` nodefault. `?` = user-created (set from the command line or configs, not registered by code); these rows are left out of `cvars.tsv`.

### User-created cvars

A cvar created from the command line or a config carries `CVAR_USER_CREATED` and is printed with `?` (`src/qcommon/common.c` `Com_StartupVariable`, `src/qcommon/cvar.c` `Cvar_List_f`); `parse()` drops those rows. As soon as mod code registers a cvar that already exists, the engine clears the flag and takes the code's default as `resetString` (`Cvar_Get`), so a surviving row is code-registered and `default` is the code default.

The run has no configs, so the only `?` row is the marker cvar `dump_marker` set on the command line. `parse()` warns if it is missing (the flag column moved, so user-created cvars would be dumped as if the mod registered them) and if other `?` rows exist.

## Caveats

- etpro is known to be incompatible with ET: Legacy: its cgame segfaults during map load, so its run always ends in the failed list and no dump is written.
- `value` is what the engine or mod set at startup; `default` is the code default.
- Missing client cvars can include cvars a mod reads without registering; a cvar the profile sets but the mod never registers is user-created and thus not in the dumps.
- The engine side comes from the local source checkout, which may be newer than the dumped build; the mod side matches the binaries of the run, kept in `modules.tsv`.
- All mods run on the engine build of one client, so engine cvars and commands are the same for every mod; they differ from the other arch's release if its version differs.
- `+lookup`, `-lookup`, `+lookdown`, `-lookdown`, `configstrings` are engine commands that mods may remove (`src/qcommon/cmd.c` `Cmd_RemoveCommandSafe`). The legacy cgame removes them, so they appear as "added" for mods that keep them.
- A mod whose client module crashes on the ET: Legacy engine can't be dumped; the report names the game's error.
"""


def selftest():
    assert table([], ["name"]) == "none\n"
    assert table([{"name": "a|b", "x": ""}], ["name", "x"]) == "| name | x |\n|---|---|\n| a\\|b |   |\n"
    base, mod = {"a": {"name": "A"}, "b": {"name": "B"}}, {"b": {"name": "B"}, "c": {"name": "C"}}
    assert diff(base, mod) == ([{"name": "C"}], [{"name": "A"}])
    assert is_client({"side": "client", "flags": "A"}) and not is_client({"side": "client", "flags": "AR"})
    assert not is_client({"side": "server", "flags": "A"}) and not is_client({"side": "client", "flags": "s"})
    assert all((p / "cvars.tsv").exists() for p in dumps().values())
    print("selftest ok")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--selftest", action="store_true")
    selftest() if ap.parse_args().selftest else main()
