#!/usr/bin/env python3
"""Compare the cvars the profile sets against each mod's dump.

Usage: python3 diff_profile.py   (run after dump_cvars.py + build_docs.py; needs ETLEGACY_SRC in settings.conf (asked by deploy.sh) or the environment)
       python3 diff_profile.py --selftest
Output: research/dumps/<mod>_<version>/diff_profile.md per mod, research/dumps/profile_unused.md overall.

Only live files count: the exec chain from <fs_homepath>/<mod>/autoexec*.cfg (startup, mod switch and
the map/team autoexecs linked into that mod folder), followed through every `exec` in files and aliases.
"""
import argparse
from pathlib import Path

from build_docs import dumps, load, table
from dump_cvars import engine_cvars
from helpers.settings import HOMEPATH, REPO  # on sys.path through dump_cvars

OUT = Path(__file__).resolve().parent
SET = {"set", "seta", "sets", "setu"}
# commands whose first argument is a cvar
CVAR_ARG = {"reset", "toggle", "cycle", "unset"}


def tokens(line):
    """Split a cfg line like the engine: quotes group, `//` outside quotes ends the line, `;` separates."""
    cmds, words, word, quoted, i = [], [], None, False, 0
    while i < len(line):
        c = line[i]
        if quoted:
            if c == '"':
                quoted = False
            else:
                word += c
        elif c == '"':
            quoted, word = True, word or ""
        elif line.startswith("//", i):
            break
        elif c in " \t;":
            if word is not None:
                words.append(word)
                word = None
            if c == ";" and words:
                cmds.append(words)
                words = []
        else:
            word = (word or "") + c
        i += 1
    if word is not None:
        words.append(word)
    return cmds + [words] if words else cmds


def scan(text, found, execs, where):
    """Collect (kind, name, value, file) of every cvar-like name a command string sets; alias and
    bind bodies are scanned too, since scripts change cvars from there."""
    for line in text.splitlines():
        # commented-out seta = cvar deliberately left at its default, counts as configured
        if line.lstrip().startswith("//") and (cmds := tokens(line.lstrip()[2:])) and cmds[0][0].lower() == "seta":
            found.append(("commented", cmds[0][1], " ".join(cmds[0][2:]), where))
            continue
        for words in tokens(line):
            head = words[0].lower()
            if head in SET and len(words) > 1:
                body = " ".join(words[2:])
                found.append((head, words[1], body, where))
                if head != "seta":  # seta holds values only (docs/conventions.md), set may hold a script
                    scan(body, found, execs, where)
            elif head == "bind" and len(words) > 2:
                scan(" ".join(words[2:]), found, execs, where)
            elif head == "vstr" or head.startswith(("+", "-")):
                continue
            elif head in CVAR_ARG and len(words) > 1:
                found.append((head, words[1], " ".join(words[2:]), where))
            elif head == "exec" and len(words) > 1:
                execs.append(words[1])
            elif len(words) > 1:  # "<cvar> <value>"; a bare name alone only prints the cvar or runs a command
                found.append(("bare", words[0], " ".join(words[1:]), where))


def chain(mod):
    """(found, unresolved) for all live files of one mod. exec paths resolve like the engine's search
    path: the mod folder first (symlinks into the profile), then etmain."""
    base = HOMEPATH
    todo, seen, found, unresolved = sorted((base / mod).glob("autoexec*.cfg")), set(), [], set()
    while todo:
        path = todo.pop().resolve()
        if path in seen or not path.is_relative_to(REPO):
            continue
        seen.add(path)
        execs = []
        scan(path.read_text(encoding="utf-8", errors="replace"), found, execs, str(path.relative_to(REPO)))
        for e in execs:
            name = e if e.endswith(".cfg") else e + ".cfg"
            hit = next((p for p in (base / mod / name, base / "etmain" / name) if p.exists()), None)
            todo.append(hit) if hit else unresolved.add(name)
    return found, unresolved


def configured(found, cvars):
    """{name: row} of found names that are cvars of this mod; the last write in the chain wins."""
    rows = {}
    for kind, name, value, where in found:
        if name.lower() in cvars:
            rows[name.lower()] = {"name": name, "value": value, "file": where, "kind": kind}
    return rows


def diff_doc(mod_name, cfg, client, cvars):
    missing = [client[k] for k in sorted(client.keys() - cfg.keys())]
    server = [cfg[k] | {"side": cvars[k]["side"]} for k in sorted(cfg) if k not in client]
    text = (f"# {mod_name} client cvars vs profile\n\n"
            f"Generated by `diff_profile.py`. Compares client-side cvars (see README) from the mod dump (`cvars.tsv`) "
            f"against every cvar the profile sets in this mod's live exec chain (`set`/`seta`, a bare `<cvar> <value>`, "
            f"`reset`/`toggle`/`cycle`, also inside `set` alias and bind strings, and commented-out `//seta`). "
            f"Names compared case-insensitively; `file` = last place in the chain that sets it.\n\n"
            f"Missing = client cvar in {mod_name}, never set by the profile. "
            f"Not client = set by the profile, but a server-side or server-set cvar in {mod_name} (no effect as a client).\n\n")
    text += f"## Missing in profile ({len(missing)})\n\n{table(missing, ['name', 'flags', 'source', 'default'])}\n"
    text += f"## Not client-side ({len(server)})\n\n{table(server, ['name', 'value', 'file', 'side'])}\n"
    return text


def main():
    # first: exits without the source before any file is written
    engine_client, engine_server = engine_cvars()
    folders = dumps()
    all_cvars, all_cmds, all_found, aliases = set(), set(), [], set()
    for mod, folder in folders.items():
        cvars, client, cmds = load(folder)
        found, unresolved = chain(mod)
        all_cvars |= cvars.keys()
        all_cmds |= cmds.keys()
        all_found += found
        aliases |= {n.lower() for kind, n, _, _ in found if kind in SET - {"seta"}}
        (folder / "diff_profile.md").write_text(diff_doc(folder.name, configured(found, cvars), client, cvars), encoding="utf-8")
        print(f"[{folder.name}] see diff_profile.md" + (f"; unresolved execs: {', '.join(sorted(unresolved))}" if unresolved else ""))

    # seta'd, reset/toggled or run bare, yet neither a cvar nor a command in any mod, nor a script alias
    unused = {}
    for kind, name, value, where in all_found:
        n = name.lower()
        if kind in CVAR_ARG | {"seta", "bare", "commented"} and not ({n} & (all_cvars | all_cmds | aliases)):
            unused.setdefault(n, {"name": name, "value": value, "file": where, "kind": kind})
    # the engine registers some cvars only on one code path (sound backend, renderer), so a dump misses them
    engine = {**engine_server, **engine_client}
    conditional = [unused[k] | {"registered in": engine[k]} for k in sorted(unused) if k in engine]
    rows = [unused[k] for k in sorted(unused) if k not in engine]
    text = (f"# Profile cvars not found in any mod\n\n"
            f"Generated by `diff_profile.py`. Names the live exec chains set via `seta`, `reset`/`toggle`/`cycle`, a bare "
            f"`<name> <value>` or a commented-out `//seta` that are neither a cvar nor a command in any dumped mod "
            f"({', '.join(folders)}) nor a script alias (`set`).\n\n"
            f"## Engine cvars missing from the dumps ({len(conditional)})\n\n"
            f"Registered by the engine (ET: Legacy source), but only on a code path the dump run didn't take, e.g. the "
            f"SDL2 sound backend while `s_initsound 2` selects OpenAL. They take effect only when that path runs.\n\n"
            f"{table(conditional, ['name', 'value', 'file', 'kind', 'registered in'])}\n"
            f"## Not existing ({len(rows)})\n\n"
            f"Not registered by the engine source either: setting them has no effect in these mods.\n\n"
            f"{table(rows, ['name', 'value', 'file', 'kind'])}")
    (OUT / "profile_unused.md").write_text(text, encoding="utf-8")
    print(f"unused (any mod): {len(rows)}, engine code-path only: {len(conditional)}, see profile_unused.md")


def selftest():
    assert tokens('set a "b; c" d; bind x "+vstr e f" // g; h') == [["set", "a", "b; c", "d"], ["bind", "x", "+vstr e f"]]
    found, execs = [], []
    scan('seta cg_fov "90"\n//seta r_x "1"\nset al "cg_drawGun 2; reset cg_y; vstr z; exec p/q.cfg"\nbind x "+attack; m_pitch 0.01"\nname',
         found, execs, "f")
    assert [(k, n) for k, n, _, _ in found] == [("seta", "cg_fov"), ("commented", "r_x"), ("set", "al"), ("bare", "cg_drawGun"),
                                               ("reset", "cg_y"), ("bare", "m_pitch")], found
    assert execs == ["p/q.cfg"], execs
    assert configured(found, {"cg_fov": {}, "m_pitch": {}}).keys() == {"cg_fov", "m_pitch"}
    print("selftest ok")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--selftest", action="store_true")
    selftest() if ap.parse_args().selftest else main()
