#!/usr/bin/env python3
"""HUD values: keeps the aliases that reset the legacy HUD in step with the HUD file.

Scripts change the popupmessages component in game with editcomponent (echo menus, default/mods/legacy/mod_general.cfg)
and must put it back where the HUD editor left it. The HUD file is personal, so the matching aliases go into a
generated block of user.cfg, which runs after mod_general.cfg and overrides its stock HUD fallback:
- popupmessagesNormal: y, w, h, feedStayTime and feedFadeTime of the HUD file
- popupmessagesMenu:   y moved so that the bottom edge stays where the HUD file has it
The commands themselves are the ones of mod_general.cfg, only these numbers are replaced.

HUD file: the highest <profile>/huds/hud_v<n>.dat; HUD: cg_altHud of user.cfg, else of <profile>/cvars.cfg.
Position (src/cgame/cg_draw_hud.c CG_CalculateComponentLocation): the file stores it relative to an anchor,
editcomponent takes the absolute top edge on the 640x480 screen.

Usage: tools/helpers/hudvalues.py   (called by deploy.sh; rewrites the block in user.cfg, prints what it did)
       tools/helpers/hudvalues.py --selftest
"""
import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # tools/: this module also runs as a command
from helpers.common import write_atomic  # noqa: E402
from helpers.settings import PROFILE, REPO  # noqa: E402

USER_CFG = REPO / "user.cfg"
HUDS = REPO / PROFILE / "huds"
TEMPLATES = REPO / PROFILE / "mods" / "legacy" / "mod_general.cfg"
COMPONENT = "popupmessages"
BEGIN = "// HUD VALUES (generated by deploy.sh from the HUD file, rewritten on every run: change the HUD in the HUD editor instead)"
END = "// HUD VALUES END"
LOADED = "USER SETTINGS LOADED"
SCREEN_H = 480
# share of the height from the top edge to each anchor point (anchorPoint_t, CG_ComputeRectBasedOnPoint):
# top left, top middle, top right, middle right, bottom right, bottom middle, bottom left, middle left, center
ANCHOR_Y = (0, 0, 0, .5, 1, 1, 1, .5, .5)
# the built-in HUD (cg_draw_hud.c CG_setDefaultHudValues), for what a HUD of the file leaves out
STOCK = {"rect": {"x": 4, "y": 245, "w": 422, "h": 96}, "anchor": 0, "parent": {"anchor": 0, "component": None},
         "feedStayTime": 2000, "feedFadeTime": 2500}


class Skip(Exception):
    """The HUD file can't be turned into values: the block stays as it is."""


def version(path):
    return int(re.fullmatch(r"hud_v(\d+)\.dat", path.name)[1])


def component(huds, name):
    """The component of a HUD with the values it leaves out taken from its parent HUD, as the game does."""
    hud = next((h for h in huds if h.get("name") == name), None)
    if hud is None:
        raise Skip(f'no HUD "{name}" (cg_altHud) in the HUD file')
    parent = hud.get("parent")
    # ponytail: only parents by name, a broken parent chain falls back to the built-in HUD
    base = component(huds, parent) if isinstance(parent, str) and parent != name else STOCK
    return {**base, **hud.get("components", {}).get(COMPONENT, {})}


def values(comp):
    """y (absolute top edge), w, h, feedStayTime, feedFadeTime of a component."""
    if comp["parent"].get("component"):
        # ponytail: screen anchors only; a component hanging on another one needs that one's position (recursive)
        raise Skip(f'{COMPONENT} is anchored to the component "{comp["parent"]["component"]}", only screen anchors are supported')
    rect = comp["rect"]
    y = rect["y"] - rect["h"] * ANCHOR_Y[comp["anchor"]] + SCREEN_H * ANCHOR_Y[comp["parent"]["anchor"]]
    return y, rect["w"], rect["h"], comp["feedStayTime"], comp["feedFadeTime"]


def read(path, name):
    return values(component(json.loads(path.read_text("utf-8"))["huds"], name))


def alt_hud(*texts):
    """cg_altHud of the first cfg text that sets it."""
    for text in texts:
        found = re.findall(r'^[ \t]*seta?[ \t]+cg_altHud[ \t]+"?([^"\n]*?)"?[ \t]*(?://.*)?$', text, re.M)
        if found:
            return found[-1]
    return "default"


def template(text, alias):
    found = re.search(rf'^[ \t]*set[ \t]+{alias}[ \t]+"([^"\n]*)"', text, re.M)
    if not found:
        raise Skip(f"no alias {alias} in {TEMPLATES.relative_to(REPO)}")
    return found[1]


def put(command, **fields):
    """The editcomponent command with the numbers of these fields replaced."""
    for field, number in fields.items():
        command, count = re.subn(rf"\b{field} \S+", f"{field} {number:g}", command)
        if count != 1:
            raise Skip(f'"{field} <number>" not found once in: {command}')
    return command


def block(templates, y, w, h, stay, fade):
    normal = put(template(templates, "popupmessagesNormal"), y=y, w=w, h=h, feedStayTime=stay, feedFadeTime=fade)
    menu = template(templates, "popupmessagesMenu")
    menu = put(menu, y=y + h - float(re.search(r"\bh (\S+)", menu)[1]))  # lines are drawn upward from the bottom edge
    return "\n".join((BEGIN, f'set popupmessagesNormal "{normal}"', f'set popupmessagesMenu "{menu}"', END))


def update(text, new):
    """user.cfg with the block replaced, or added before the load marker so that it stays the last line."""
    old = re.search(rf"^{re.escape(BEGIN[:13])}.*?^{re.escape(END)}$", text, re.M | re.S)
    if old:
        return text[:old.start()] + new + text[old.end():]
    lines = text.split("\n")
    at = next((i for i, line in enumerate(lines) if LOADED in line), len(lines))
    return "\n".join(lines[:at] + [new, ""] + lines[at:])


def main():
    if not USER_CFG.exists():
        return
    files = sorted(HUDS.glob("hud_v*.dat"), key=version)
    if not files:
        print(f"no HUD file in {HUDS.relative_to(REPO)}/, the stock HUD values of mod_general.cfg apply")
        return
    text = USER_CFG.read_text("latin1")
    name = alt_hud(text, (REPO / PROFILE / "cvars.cfg").read_text("latin1"))
    try:
        found = read(files[-1], name)
        new = update(text, block(TEMPLATES.read_text("latin1"), *found))
    except (Skip, OSError, ValueError, KeyError, IndexError, TypeError) as error:
        print(f"⚠️  HUD values in user.cfg not updated ({files[-1].name}): {error if isinstance(error, Skip) else repr(error)}")
        return
    # servers with an older legacy load the file of their HUD version
    for path in files[:-1]:
        try:
            if read(path, name) != found:
                print(f"⚠️  {path.name} has other {COMPONENT} values than {files[-1].name}: the HUD values fit only servers that load {files[-1].name}")
        except Exception:  # an unreadable older file changes nothing for the newest one
            pass
    if new != text:
        write_atomic(USER_CFG, new)
        print(f'user.cfg: HUD values updated from {files[-1].name} (HUD "{name}")')


def selftest():
    huds = [{"name": "base", "parent": None, "components": {COMPONENT: {"rect": {"x": 1, "y": 50, "w": 300, "h": 80},
                                                                           "anchor": 0, "parent": {"anchor": 7, "component": None}}}},
            {"name": "child", "parent": "base", "components": {COMPONENT: {"feedStayTime": 900}}},
            {"name": "bare", "parent": False, "components": {}},
            {"name": "hung", "parent": "base", "components": {COMPONENT: {"parent": {"anchor": 0, "component": "chat"}}}}]
    assert values(component(huds, "base")) == (290, 300, 80, 2000, 2500)  # 50 below the screen middle
    assert values(component(huds, "child")) == (290, 300, 80, 900, 2500)  # the rest from the parent HUD
    assert values(component(huds, "bare")) == (245, 422, 96, 2000, 2500)  # built-in HUD
    bottom = {**STOCK, "rect": {"x": 0, "y": -10, "w": 100, "h": 60}, "anchor": 6, "parent": {"anchor": 6, "component": None}}
    assert values(bottom)[0] == 410  # bottom left corner 10 above the screen bottom
    for name in ("hung", "missing"):
        try:
            component(huds, name) and values(component(huds, name))
            raise AssertionError(name)
        except Skip:
            pass

    assert alt_hud('seta cg_altHud "mine"  // note\n', 'seta cg_altHud "other"') == "mine"
    assert alt_hud('// seta cg_altHud "off"\n', "set cg_altHud 2\n") == "2" and alt_hud("") == "default"

    templates = ('set popupmessagesNormal "editcomponent popupmessages y 1 w 2 h 3 feedStayTime 4 feedFadeTime 5"  // note\n'
                 'set popupmessagesMenu "editcomponent popupmessages y 1 w 600 h 240 feedStayTime 9 feedFadeTime 8"\n')
    new = block(templates, 290.5, 300, 80, 900, 2500)
    assert 'popupmessagesNormal "editcomponent popupmessages y 290.5 w 300 h 80 feedStayTime 900 feedFadeTime 2500"' in new
    assert 'popupmessagesMenu "editcomponent popupmessages y 130.5 w 600 h 240 feedStayTime 9 feedFadeTime 8"' in new  # bottom edge 370.5
    try:
        block("set popupmessagesNormal \"editcomponent popupmessages w 2\"\n", 1, 2, 3, 4, 5)
        raise AssertionError("template without y")
    except Skip:
        pass

    cfg = f'set a "1"\n\necho "^5  *** {LOADED}!"'
    first = update(cfg, new)
    assert first == f'set a "1"\n\n{new}\n\necho "^5  *** {LOADED}!"'
    assert update(first, new) == first  # rerun changes nothing
    other = block(templates, 100, 300, 80, 900, 2500)
    assert update(first, other) == first.replace(new, other) and update("set a 1", new).endswith(END + "\n")
    print("selftest ok")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--selftest", action="store_true")
    selftest() if ap.parse_args().selftest else main()
