"""Server menu pages: the echo menu cfgs of tools/servermenu.py, built from rows of helpers.serverapi.summarize().

A page echoes its servers and binds the number keys to connect, TAB execs the next page (the same one if there is
only one, which refreshes it). A server shows as name, playing humans+spectators+bots/slots, map, ping, mod, the columns
aligned with spaces (the popup font courbd is monospaced). order() sorts the servers by playing humans, then
spectators and bots; servers that don't answer come last. The last entry hosts LOCAL_MAP locally (`disconnect; map`: the game
drops the server it is on and hosts in the mod it runs). Also used by tools/keymap/keymap.py with made-up servers.
"""
import re

from helpers.common import COLOR, clean, strip_colors
from helpers.settings import MENU, VSAY

EXEC = "profile/servermenu"  # the profile link of deploy.sh in each mod folder
KEYS = ("1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "US_MINUS", "US_EQUALS")
NAME_LEN = 24
MAP_LEN = 16
LOCAL_MAP = "goldrush"  # stock map: every mod has it


def cut(name, length=NAME_LEN):
    """Name with its color codes, cut to `length` visible characters."""
    out, visible = "", 0
    for m in re.finditer(rf"{COLOR}|.", clean(name).strip()):
        if visible == length:
            break
        out += m.group()
        visible += len(m.group()) == 1
    return out.rstrip().rstrip("^")  # a trailing ^ would swallow the color code that follows


def width(text):
    """Visible characters of a text with color codes."""
    return len(strip_colors(text))


def pad(text, size):
    return text + " " * (size - width(text))


def cells(row):
    """[name, players, map, ping, mod] of a row; players as [playing, spectators, bots, slots] ("" if unknown), or "offline"."""
    name = cut(row["name"]) + MENU["text"]
    if row["playing"] is None:
        return [name, "offline", "", "", ""]
    numbers = [row["playing"], row["spec"], row["bots"], row["slots"]]
    ping = f"{row['ping']}ms" if row["ping"] is not None else ""
    return [name, ["" if n is None else str(n) for n in numbers], clean(row["map"])[:MAP_LEN], ping, clean(row["mod"])]


def players(numbers, sizes):
    """playing+spectators+bots/slots, every number right-aligned in its own column so the last digits line up;
    playing humans colored only when the spectators are known (without P they are all humans)."""
    t = MENU["text"]
    playing, spec, bots, slots = (n.rjust(size) for n, size in zip(numbers, sizes))
    colored = MENU["playing"] if numbers[1] else t
    text = f"{colored}{playing}{t}{'+' if numbers[1] else ' '}{MENU['spec']}{spec}{t}+{MENU['bots']}{bots}{t}"
    return text + (f"/{slots}" if numbers[3] else " " * (sizes[3] + 1))


def table(rows):
    """Lines of the rows with the columns aligned by spaces: the popup font (courbd) is monospaced."""
    grid = [cells(r) for r in rows]
    numbers = [c[1] for c in grid if isinstance(c[1], list)]
    digits = [max((len(n[i]) for n in numbers), default=0) for i in range(4)]
    for c in grid:
        if isinstance(c[1], list):
            c[1] = players(c[1], digits)
    sizes = [max((width(c[i]) for c in grid), default=0) for i in range(5)]
    out = []
    for c in grid:
        ping = " " * (sizes[3] - width(c[3])) + c[3]  # right-aligned
        out.append("  ".join([pad(c[0], sizes[0]), pad(c[1], sizes[1]), pad(c[2], sizes[2]), ping, c[4]]).rstrip())
    return out


def order(rows):
    return sorted(rows, key=lambda r: (r["playing"] is None, -(r["playing"] or 0), -(r["spec"] or 0), -r["bots"]))


def connect_say(row, vsay):
    """Sets the vsay `vsay` (id) of a number key that scripts/servermenu.cfg sends while its toggle is on: the full hostname in its own colors."""
    g = VSAY["global"]
    return f"set connectSayText vsay {vsay} {g}Connecting to {cut(row['name'], 999)}{VSAY['punct']}."


def pages(rows, size, stamp, vsay="Bye"):
    """{file name: cfg text} of one page set; the columns are aligned over all pages. vsay: id of the connect say."""
    lines = table(rows) + [f"LOCALHOST  {LOCAL_MAP}"]
    actions = [f'vstr resetLayers; {connect_say(row, vsay)}; vstr connectSay; set timerDone connect {row["address"]}; vstr timer400' for row in rows]
    actions.append(f"vstr resetLayers; disconnect; map {LOCAL_MAP}")  # disconnect: a map load on the local host keeps its pure state, the restart would mount all of dlcache and run out of open files
    count = -(-len(lines) // size)
    out = {}
    for page in range(count):
        part = slice(page * size, (page + 1) * size)
        of = f" {page + 1}/{count}" if count > 1 else ""
        tab = "next page" if count > 1 else "refresh"
        cfg = ["// Generated by tools/servermenu.py, rewritten every few seconds while it runs", "vstr popupsMenu",
               f'echo "{MENU["head"]}SERVERS{of} {stamp} {MENU["nav"]}TAB {tab}{MENU["head"]}:"']
        if not rows:
            cfg.append(f'echo "{MENU["text"]}No favorite servers: add some in the server browser"')
        cfg += [f'echo "{MENU["key"]}{f"{n}.":<4}{MENU["text"]}{text}"' for n, text in enumerate(lines[part], 1)]
        cfg.append("vstr unbindNumbers")
        cfg += [f'bind {key} "{action}"' for key, action in zip(KEYS, actions[part])]
        cfg.append(f'bind TAB "execq {EXEC}/p{size}_{(page + 1) % count}.cfg"')  # execq: a key press prints no "execing" line
        out[f"p{size}_{page}.cfg"] = "\n".join(cfg) + "\n"
    return out
