#!/usr/bin/env python3
"""Server configs: tells the game which server it is on, so it can exec that server's settings and voice chat.

Runs next to the game and follows its console log (tools/common.py follow). A connect ("<address> resolved to
<ip:port>", src/client/cl_main.c CL_Connect_f) names only the address, so the server is asked for its name
(tools/serverapi.py) and the name is looked up in default/serverconfigs/servers.tsv; a server seen before is
recognized at once from history.tsv, the answer then corrects it. A server that doesn't answer (map change, restart,
its rate limit) is asked again after 2, 4, 8, ... up to 60 s, until it answers or the game moves on. A locally hosted map ("----- Server
Initialization ----", src/server/sv_init.c SV_SpawnServer) is the id "local". Written to default/serverconfigs/:
- current.cfg: execs default.cfg, then <id>.cfg if the id has one. Its guard applies them only when another id was
  applied last, so the game execs it on many events (map load, team and class change, voice chat) and catches up
  whenever this tool was slower than the game.
- current_vsay.cfg: exec'd each time the voice chat opens; puts the server's voice chat (scripts/vsays/servers/<id>/,
  tools/voicemenu.py) on TAB, or nothing.

At start (and with --check) every name a server cfg sets is looked up in default.cfg, which runs before every server
cfg: a name it doesn't mention keeps the server's value on all other servers, so it is reported (warning only).

Usage: tools/serverconfig.py                                      follow the game (Ctrl+C stops)
       tools/serverconfig.py add <id> [address] [--match <text>]  row in servers.tsv, <id>.cfg if missing; the
                                                                  address defaults to the last connect in the log,
                                                                  the text to the tag at the start of the server's name;
                                                                  an id that has a row is replaced after asking
       tools/serverconfig.py --check | --selftest
"""
import argparse
import contextlib
import io
import re
import sys
import tempfile
import time
from pathlib import Path

from common import STAMP, clean, find_log, follow, strip_colors, write_atomic
from serverapi import CONFIGS, ID, ID_RULE, SERVERS, adr_string, history, hostname, identify, remember, resolve, server_tag, servers
from settings import MENU, PROFILE, REPO

EXEC = "profile/serverconfigs"  # the profile link of deploy.sh in each mod folder
VOICE = REPO / PROFILE / "scripts/vsays/servers"
VOICE_EXEC = "profile/scripts/vsays/servers"
CONNECT = re.compile(r"\S+ resolved to (\d+\.\d+\.\d+\.\d+:\d+|\[[^\]\s]+\]:\d+)")  # one word in front: not the "MOTD: resolving ..." line; IPv6 is "[ip]:port"
LOCAL = "----- Server Initialization ----"
RETRY, RETRY_MAX = 2, 60  # seconds until a server that didn't answer is asked again: doubled after every try, up to the maximum
GENERATED = {"default", "current", "current_vsay"}  # cfgs of serverconfigs/ that are no server's settings
NAME = re.compile(r'\s*(?:(?:set[asu]?|bind|reset|toggle|cycle)\s+)?"?([^\s";]+)')
NO_NAME = {"exec", "execq", "vstr", "echo", "wait"}


def event(line):
    """"ip:port" ("[ip]:port" for IPv6) the game connects to, "local" when it hosts a map itself, None for every other log line."""
    text = STAMP.sub("", line).strip()
    if text == LOCAL:
        return "local"
    m = CONNECT.fullmatch(text)
    return m and m.group(1)


def settings_cfg(server):
    """current.cfg of a settings id. serverLast runs the alias of the id applied last, which is null while this file
    runs if that is this id; else it applies. scripts set serverLast to "vstr serverApply" to force it (serverForce).
    execq: a key press can apply them (class key, voice chat), which prints no "execing" line."""
    own = "" if server == "default" else f"execq {EXEC}/{server}.cfg; "
    return "\n".join([
        "// Generated by tools/serverconfig.py: settings of the server the game is on, applied once per server (docs/serverconfigs.md)",
        f'set serverApply "execq {EXEC}/default.cfg; {own}set serverLast vstr serverIs_{server}"',
        f'set serverIs_{server} "vstr null"',
        "vstr serverLast",
        f'set serverIs_{server} "vstr serverApply"']) + "\n"


def vsay_cfg(server, tag):
    """current_vsay.cfg: the TAB line and bind of the voice chat's first page; no server page, no TAB."""
    head = "// Generated by tools/serverconfig.py: TAB of the voice chat on this server (scripts/vsays/chat/categories.cfg)\n"
    if not server:
        return head
    return head + f'echo "{MENU["nav"]}TAB {tag}{MENU["nav"]} Voice chat"\nbind TAB "execq {VOICE_EXEC}/{server}/{server}.cfg"\n'


def write(server, name="", rows=(), out=CONFIGS, voice=VOICE):
    """Writes current.cfg and current_vsay.cfg for a server id (None: no row of servers.tsv matches) and returns the ids
    used: settings fall back to "default" without <id>.cfg, the voice chat to None without a page folder. A file is
    only replaced when its text changes."""
    settings = server if server and (out / f"{server}.cfg").exists() else "default"
    chat = server if server and (voice / server / f"{server}.cfg").exists() else None
    tag = chat and (server_tag(server, [name], rows) or f"[{server}]")
    out.mkdir(parents=True, exist_ok=True)
    for file, text in (("current.cfg", settings_cfg(settings)), ("current_vsay.cfg", vsay_cfg(chat, tag))):
        try:
            same = (out / file).read_text("latin1") == text
        except OSError:
            same = False
        if not same:
            write_atomic(out / file, text)
    return settings, chat


def ask(target, name=hostname):
    """Asks the server "ip:port" for its name once and brings the files up to the answer; False without one."""
    name = name(target)
    if not name:
        return False
    remember(target, name)
    rows = servers()
    write(identify(name, rows), name, rows)
    return True


def settle(target):
    """Brings the files up to where the game is now (None: no server, "local", or "ip:port"): at once from the
    history, then from the server's own answer. False if the server has yet to answer."""
    if target in (None, "local"):
        write(target)
        return True
    rows = servers()
    name = history().get(target, "")
    write(identify(name, rows), name, rows)
    return ask(target)


def pauses():
    """Seconds to wait before each further try."""
    pause = RETRY
    while True:
        yield pause
        pause = min(pause * 2, RETRY_MAX)


def unreset(text, default):
    """Names a server cfg sets (after set/seta/bind/..., else the first word of a line) that default.cfg doesn't mention
    anywhere: a reset can be indirect ("vstr fovNormal  // cg_fov"), so a comment counts."""
    # ponytail: only the first command of a line is looked at; split on ";" outside quotes when cfgs chain commands
    out = []
    for line in text.splitlines():
        m = NAME.match(line.split("//")[0])
        if m and m.group(1).lower() not in NO_NAME and m.group(1) not in out \
                and not re.search(rf"(?<!\w){re.escape(m.group(1))}(?!\w)", default, re.I):
            out.append(m.group(1))
    return out


def check(out=CONFIGS):
    """Warns about every name of a server cfg that default.cfg doesn't reset; returns the warnings."""
    try:
        default = (out / "default.cfg").read_text("latin1")
    except OSError:
        default = ""
    lines = [f"⚠️  serverconfigs/{f.name}: {name} is not in default.cfg, so it keeps this value on other servers"
             for f in sorted(out.glob("*.cfg")) if f.stem not in GENERATED
             for name in unreset(f.read_text("latin1"), default)]
    for line in lines:
        print(line, file=sys.stderr)
    return lines


def last_connect():
    """"ip:port" of the last connect in the game's log, None if there is none or the game hosts a map since."""
    path = find_log()
    events = [e for e in map(event, path.read_text(errors="replace").splitlines()) if e] if path else []
    return events[-1] if events and events[-1] != "local" else None


def guess(name):
    """The text proposed for a server name: its first word up to the first sign that ends a tag ("ABc|Clan" -> "ABc|")."""
    m = re.match(r"\W*\w+[^\w\s]?", strip_colors(name).strip())
    return m.group() if m else ""


def with_row(lines, server, text):
    """(lines of servers.tsv with the row "<id><TAB><text>", texts it replaces): the row takes the place of the id's
    first row and its other rows go; a new id is appended."""
    out, old = [], []
    for line in lines:
        name, sep, was = line.partition("\t")
        if sep and name.strip() == server:
            if not old:
                out.append(f"{server}\t{text}")
            old.append(was.strip())
        else:
            out.append(line)
    return (out if old else out + [f"{server}\t{text}"]), old


def add(server, address, text):
    if not ID.fullmatch(server):
        sys.exit(f"id '{server}': {ID_RULE}")
    address = address or last_connect()
    if not address:
        sys.exit("no address given and no connect in the game's log")
    name = hostname(address)
    if not name:
        sys.exit(f"{address} doesn't answer")
    text = text or guess(name)
    if not text or "\t" in text or identify(name, [(server, text)]) != server:
        sys.exit(f"the server's name doesn't contain '{text}': {name}")
    CONFIGS.mkdir(parents=True, exist_ok=True)
    lines = SERVERS.read_text("latin1").splitlines() if SERVERS.exists() else \
        ["# <id><TAB><text in the server name>, the first matching row wins (docs/serverconfigs.md)"]
    lines, old = with_row(lines, server, text)
    if old and old != [text]:
        print(f"⚠️  '{server}' is in {SERVERS.name} already, with: {' | '.join(old)}", file=sys.stderr)
        if not sys.stdin.isatty() or input(f"Replace with '{text}'? [y/N] ").strip().lower() != "y":  # no terminal: nobody to ask
            sys.exit(f"{SERVERS.name} unchanged")
    write_atomic(SERVERS, "\n".join(lines) + "\n")
    cfg = CONFIGS / f"{server}.cfg"
    if not cfg.exists():
        cfg.write_text(f"// Settings on the servers of '{server}' (docs/serverconfigs.md): absolute values only, and every name set here gets its normal value in default.cfg\n", "latin1")
    remember(adr_string(resolve(address)), name)
    print(f"{name}\n{SERVERS.relative_to(REPO)}: {server}\t{text}\n{cfg.relative_to(REPO)}")
    first = identify(name, servers())
    if first != server:
        print(f"⚠️  the earlier row of '{first}' matches this server first", file=sys.stderr)


def run():
    check()
    print(f"Server configs: following the game -> {CONFIGS} (Ctrl+C stops)")
    done, target, wait, due = object(), None, None, 0
    try:
        for line in follow():
            if line is None:  # a new game session is on no server
                target = None
            elif line:
                target = event(line) or target
            elif target != done:  # end of the log: act on the last event only, not on every connect of a replay
                done, wait = target, None if settle(target) else pauses()
                due = time.monotonic() + next(wait) if wait else 0
            elif wait and time.monotonic() >= due:  # between the tries the log is followed on, so a new connect is not held up
                wait = None if ask(target) else wait
                due = time.monotonic() + next(wait) if wait else 0
    except KeyboardInterrupt:
        pass


def selftest():
    assert event("       0 192.0.2.7:27980 resolved to 192.0.2.7:27980\n") == "192.0.2.7:27980"
    assert event("  165000 my.server.org resolved to 1.2.3.4:27960\n") == "1.2.3.4:27960"
    assert event("       0 [2001:db8::1]:27961 resolved to [2001:db8::1]:27961\n") == "[2001:db8::1]:27961"
    assert event("       0 MOTD: resolving motd.example.org... resolved to 192.0.2.9:27951\n") is None
    assert event("       0 localhost resolved to loopback\n") is None and event("       0 Server: fueldump\n") is None
    assert event("    1200 ----- Server Initialization ----\n") == "local"

    xy = settings_cfg("xy").splitlines()
    assert xy[1] == f'set serverApply "execq {EXEC}/default.cfg; execq {EXEC}/xy.cfg; set serverLast vstr serverIs_xy"'
    assert xy[2:] == ['set serverIs_xy "vstr null"', "vstr serverLast", 'set serverIs_xy "vstr serverApply"']
    assert f'set serverApply "execq {EXEC}/default.cfg; set serverLast vstr serverIs_default"' in settings_cfg("default")
    assert vsay_cfg(None, None).count("\n") == 1 and vsay_cfg(None, None).startswith("//")
    nav = MENU["nav"]
    assert vsay_cfg("xy", "^1[^7xY^1]").splitlines()[1:] == [f'echo "{nav}TAB ^1[^7xY^1]{nav} Voice chat"', f'bind TAB "execq {VOICE_EXEC}/xy/xy.cfg"']

    with tempfile.TemporaryDirectory() as d:
        out, voice = Path(d) / "serverconfigs", Path(d) / "voice"
        rows = [("xy", "[xY]"), ("solo", "Solo Server")]
        assert write(None, out=out, voice=voice) == ("default", None)
        assert (out / "current.cfg").read_text() == settings_cfg("default") and (out / "current_vsay.cfg").read_text() == vsay_cfg(None, None)
        assert write("xy", "^1[^7xY^1] x", rows, out, voice) == ("default", None)  # neither a cfg nor voice pages yet
        (out / "xy.cfg").write_text("set fovLow 100\ncg_fov 100 // x\nbind F9 \"vstr a; cg_drawFPS 1\"\n\nvstr hook\n// com_maxfps 1\nseta \"r_gamma\" 2\n")
        (voice / "xy").mkdir(parents=True)
        (voice / "xy/xy.cfg").write_text("")
        (voice / "solo").mkdir()
        (voice / "solo/solo.cfg").write_text("")
        assert write("xy", '^1[^7xY"^1] x', [("xy", '[xY"]')], out, voice) == ("xy", "xy")
        assert (out / "current.cfg").read_text() == settings_cfg("xy")
        assert f"TAB ^1[^7xY'^1]{nav} Voice chat" in (out / "current_vsay.cfg").read_text()  # cfg-safe tag
        before = (out / "current.cfg").stat().st_mtime_ns
        assert write("solo", "", rows, out, voice) == ("default", "solo")  # voice pages only, name unknown
        assert f"TAB [solo]{nav} Voice chat" in (out / "current_vsay.cfg").read_text()
        write("solo", "", rows, out, voice)
        assert not list(out.glob("*.tmp")) and (out / "current.cfg").stat().st_mtime_ns > before
        same = (out / "current.cfg").stat().st_mtime_ns
        write("solo", "", rows, out, voice)
        assert (out / "current.cfg").stat().st_mtime_ns == same  # unchanged text: file left alone

        with contextlib.redirect_stderr(io.StringIO()):  # the warnings are the result here
            assert check(out) == [f"⚠️  serverconfigs/xy.cfg: {n} is not in default.cfg, so it keeps this value on other servers"
                                  for n in ("fovLow", "cg_fov", "F9", "r_gamma")]
            (out / "default.cfg").write_text('vstr fovLowNormal  // fovLow\nCG_FOV 90\nbind F9 "vstr b"\n')
            assert check(out) == ["⚠️  serverconfigs/xy.cfg: r_gamma is not in default.cfg, so it keeps this value on other servers"]
    assert [guess(n) for n in ("^1[^7xY^1] FRAGHOUSE", "^8ABc|^4Clan^9,XPSave", " {SomeName} #1", "^3Full Name", "^1")] == ["[xY]", "ABc|", "{SomeName}", "Full", ""]
    tsv = ["# head", "xy\t[xY]", "sn\tSOME", "abc\tABc|", "sn\tSOME NAME"]
    assert with_row(tsv, "sn", "Name") == (["# head", "xy\t[xY]", "sn\tName", "abc\tABc|"], ["SOME", "SOME NAME"])
    assert with_row(tsv, "new", "x y") == (tsv + ["new\tx y"], []) and with_row(tsv, "xy", "[xY]")[1] == ["[xY]"]
    wait = pauses()
    assert [next(wait) for _ in range(7)] == [2, 4, 8, 16, 32, 60, 60]
    assert ask("1.2.3.4:27960", lambda address: "") is False  # no answer: nothing is written
    assert unreset("cg_fov 1\ncg_fov 2\nexec x.cfg\nwait 5", "my_cg_fov 1") == ["cg_fov"]
    print("selftest ok")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", nargs="?", choices=["add"])
    ap.add_argument("id", nargs="?")
    ap.add_argument("address", nargs="?", help="host[:port], default: the last connect in the game's log")
    ap.add_argument("--match", metavar="TEXT", help="text in the server's name, default: the tag at its start")
    ap.add_argument("--check", action="store_true", help="only report names that default.cfg doesn't reset")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    if a.check:
        return check()
    if a.command:
        if not a.id:
            ap.error("add needs an id")
        return add(a.id, a.address, a.match)
    run()


if __name__ == "__main__":
    main()
